// Post
export const GET_POSTS_BEGIN = "GET_POSTS_BEGIN";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const CREATE_NEW_POST = "CREATE_NEW_POST";
export const UPDATE_EXISTING_POST = "UPDATE_EXISTING_POST";
export const GET_SINGLE_POST_BEGIN = "GET_SINGLE_POST_BEGIN";
export const GET_SINGLE_POST_ERROR = "GET_SINGLE_POST_ERROR";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";

// Comment
export const GET_COMMENTS_BEGIN = "GET_COMMENTS_BEGIN";
export const GET_COMMENTS_ERROR = "GET_COMMENTS_ERROR";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const CREATE_NEW_COMMENT = "CREATE_NEW_COMMENT";
export const UPDATE_EXISTING_COMMENT = "UPDATE_EXISTING_COMMENT";
export const GET_SINGLE_COMMENT_BEGIN = "GET_SINGLE_COMMENT_BEGIN";
export const GET_SINGLE_COMMENT_ERROR = "GET_SINGLE_COMMENT_ERROR";
export const GET_SINGLE_COMMENT_SUCCESS = "GET_SINGLE_COMMENT_SUCCESS";

// User
export const GET_USERS_BEGIN = "GET_USERS_BEGIN";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const UPDATE_EXISTING_USER = "UPDATE_EXISTING_USER";
export const GET_SINGLE_USER_BEGIN = "GET_SINGLE_USER_BEGIN";
export const GET_SINGLE_USER_ERROR = "GET_SINGLE_USER_ERROR";
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
