// Post
export const GET_POSTS_BEGIN = "GET_POSTS_BEGIN";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const CREATE_NEW_POST = "CREATE_NEW_POST";

export const UPDATE_EXISTING_POST = "UPDATE_EXISTING_POST";
export const GET_SINGLE_POST_BEGIN = "GET_SINGLE_POST_BEGIN";
export const GET_SINGLE_POST_ERROR = "GET_SINGLE_POST_ERROR";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
